# Generated by Django 2.0.13 on 2019-06-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fproject', '0002_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publised_date',
            new_name='published_date',
        ),
    ]
